"""
Markdown report generator
"""
import logging
import os
from datetime import datetime
from typing import Dict, Any, List
from collections import Counter


class MarkdownGenerator:
    """
    Generate daily AI trends report in Markdown format
    """

    def __init__(self, config: Dict[str, Any]):
        """
        Initialize generator with configuration

        Args:
            config: Configuration dictionary
        """
        self.config = config
        self.output_dir = config.get('output_dir', 'reports')
        self.date_format = config.get('date_format', '%Y-%m-%d')
        self.logger = logging.getLogger('MarkdownGenerator')

        # Ensure output directory exists
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)
            self.logger.info(f"Created output directory: {self.output_dir}")

    def generate(self, data: Dict[str, List[Dict]], date: datetime = None) -> str:
        """
        Generate daily report from collected data

        Args:
            data: Dictionary with source names as keys and item lists as values
            date: Report date (defaults to today)

        Returns:
            Path to generated report file
        """
        if not date:
            date = datetime.now()

        report_date = date.strftime(self.date_format)
        filename = f"{report_date}.md"
        filepath = os.path.join(self.output_dir, filename)

        self.logger.info(f"Generating report for {report_date}")

        # Generate Markdown content
        content = self._build_report_content(data, report_date)

        # Write to file
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

        self.logger.info(f"Report saved to {filepath}")
        return filepath

    def _build_report_content(self, data: Dict[str, List[Dict]], date_str: str) -> str:
        """
        Build Markdown report content

        Args:
            data: Collected data from sources
            date_str: Date string for report

        Returns:
            Markdown content string
        """
        lines = []

        # Header
        lines.append(f"# AI Trends Daily Report - {date_str}")
        lines.append("")
        lines.append(f"*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
        lines.append("")

        # Overview section
        lines.append("## 📊 Overview")
        overview_stats = self._generate_overview(data)
        lines.extend(overview_stats)
        lines.append("")

        # Hacker News section
        if 'Hacker News' in data and data['Hacker News']:
            lines.append("## 🔥 Hacker News Top AI Stories")
            hn_items = self._format_hackernews_items(data['Hacker News'])
            lines.extend(hn_items)
            lines.append("")

        # Reddit section
        if 'Reddit' in data and data['Reddit']:
            lines.append("## 💬 Reddit Hot Posts")
            reddit_items = self._format_reddit_items(data['Reddit'])
            lines.extend(reddit_items)
            lines.append("")

        # GitHub Trending section
        if 'GitHub Trending' in data and data['GitHub Trending']:
            lines.append("## 💻 GitHub Trending AI Projects")
            github_items = self._format_github_items(data['GitHub Trending'])
            lines.extend(github_items)
            lines.append("")

        # Twitter section (optional)
        if 'Twitter' in data and data['Twitter']:
            lines.append("## 🐦 AI Tweets")
            twitter_items = self._format_twitter_items(data['Twitter'])
            lines.extend(twitter_items)
            lines.append("")

        # Summary section
        if self.config.get('include_summary', True):
            lines.append("## 📈 Summary & Key Trends")
            summary = self._generate_summary(data)
            lines.extend(summary)
            lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("*This report is automatically generated by AI Daily Report Generator.*")
        lines.append("")
        lines.append(f"[View all reports](../)")
        lines.append("")

        return '\n'.join(lines)

    def _generate_overview(self, data: Dict[str, List[Dict]]) -> List[str]:
        """
        Generate overview statistics

        Args:
            data: Collected data

        Returns:
            List of overview lines
        """
        total_items = sum(len(items) for items in data.values())
        sources = [name for name, items in data.items() if items]

        lines = []
        lines.append(f"**Total items collected:** {total_items}")
        lines.append("")
        lines.append("**Active sources:**")

        for source in sources:
            count = len(data[source])
            lines.append(f"- {source}: {count} items")

        lines.append("")

        return lines

    def _format_hackernews_items(self, items: List[Dict]) -> List[str]:
        """
        Format Hacker News items

        Args:
            items: List of HN story dictionaries

        Returns:
            List of formatted lines
        """
        lines = []

        for i, item in enumerate(items, 1):
            title = item.get('title', 'Untitled')
            link = item.get('link', '')
            score = item.get('score', 0)
            comments = item.get('comments', 0)

            lines.append(f"{i}. [{title}]({link})")
            lines.append(f"   - **Score:** {score} points")
            lines.append(f"   - **Comments:** {comments}")
            lines.append("")

        return lines

    def _format_reddit_items(self, items: List[Dict]) -> List[str]:
        """
        Format Reddit items grouped by subreddit

        Args:
            items: List of Reddit post dictionaries

        Returns:
            List of formatted lines
        """
        lines = []

        # Group by subreddit
        by_subreddit = {}
        for item in items:
            subreddit = item.get('subreddit', 'unknown')
            if subreddit not in by_subreddit:
                by_subreddit[subreddit] = []
            by_subreddit[subreddit].append(item)

        for subreddit, posts in by_subreddit.items():
            lines.append(f"### r/{subreddit}")
            lines.append("")

            for i, post in enumerate(posts[:10], 1):  # Limit per subreddit
                title = post.get('title', 'Untitled')[:100]
                link = post.get('link', '')
                score = post.get('score', 0)
                comments = post.get('comments', 0)

                lines.append(f"{i}. [{title}]({link})")
                lines.append(f"   - **Score:** {score} upvotes")
                lines.append(f"   - **Comments:** {comments}")
                lines.append("")

        return lines

    def _format_github_items(self, items: List[Dict]) -> List[str]:
        """
        Format GitHub Trending items

        Args:
            items: List of GitHub repo dictionaries

        Returns:
            List of formatted lines
        """
        lines = []

        for i, item in enumerate(items, 1):
            full_name = item.get('full_name', 'unknown/unknown')
            link = item.get('link', '')
            description = item.get('description', 'No description')[:150]
            language = item.get('language', 'Unknown')
            stars = item.get('stars', 0)
            stars_today = item.get('stars_today', 0)

            lines.append(f"{i}. [{full_name}]({link})")
            lines.append(f"   - **Description:** {description}")
            lines.append(f"   - **Language:** {language}")
            lines.append(f"   - **Stars:** {stars} total, ⭐ {stars_today} today")
            lines.append("")

        return lines

    def _format_twitter_items(self, items: List[Dict]) -> List[str]:
        """
        Format Twitter items

        Args:
            items: List of tweet dictionaries

        Returns:
            List of formatted lines
        """
        lines = []

        for i, item in enumerate(items, 1):
            author = item.get('author', 'unknown')
            text = item.get('text', '')[:100]
            link = item.get('link', '')
            likes = item.get('score', 0)
            retweets = item.get('retweets', 0)

            lines.append(f"{i}. [@{author}]({link})")
            lines.append(f"   - {text}...")
            lines.append(f"   - **Likes:** {likes}, **Retweets:** {retweets}")
            lines.append("")

        return lines

    def _generate_summary(self, data: Dict[str, List[Dict]]) -> List[str]:
        """
        Generate summary and key trends

        Args:
            data: Collected data

        Returns:
            List of summary lines
        """
        lines = []

        # Collect all titles/descriptions for analysis
        all_text = []
        for source, items in data.items():
            for item in items:
                all_text.append(item.get('title', '').lower())
                if 'description' in item:
                    all_text.append(item['description'].lower())

        # Extract trending topics (simple keyword frequency)
        keywords = [
            'GPT', 'LLM', 'neural', 'transformer', 'training',
            'model', 'dataset', 'NLP', 'vision', 'generative',
            'reinforcement', 'embedding', 'RAG', 'agents'
        ]

        keyword_counts = Counter()
        for text in all_text:
            for keyword in keywords:
                if keyword.lower() in text:
                    keyword_counts[keyword] += 1

        if keyword_counts:
            lines.append("**Popular topics today:**")
            for keyword, count in keyword_counts.most_common(5):
                lines.append(f"- {keyword}: {count} mentions")
            lines.append("")

        # Source highlights
        lines.append("**Highlights by source:**")
        lines.append("")

        if 'Hacker News' in data and data['Hacker News']:
            top_hn = data['Hacker News'][0] if data['Hacker News'] else None
            if top_hn:
                lines.append(f"- Hacker News: Top story \"{top_hn['title'][:50]}...\" with {top_hn['score']} points")

        if 'GitHub Trending' in data and data['GitHub Trending']:
            top_repo = data['GitHub Trending'][0] if data['GitHub Trending'] else None
            if top_repo:
                lines.append(f"- GitHub: Most trending repo \"{top_repo['full_name']}\" with +{top_repo['stars_today']} stars today")

        if 'Reddit' in data and data['Reddit']:
            top_reddit = data['Reddit'][0] if data['Reddit'] else None
            if top_reddit:
                lines.append(f"- Reddit: Top post from r/{top_reddit['subreddit']} with {top_reddit['score']} upvotes")

        lines.append("")

        return lines


# For testing
if __name__ == "__main__":
    import sys
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    # Test data
    test_data = {
        'Hacker News': [
            {
                'title': 'New GPT-4 model released',
                'link': 'https://example.com/1',
                'score': 500,
                'comments': 150
            }
        ],
        'Reddit': [
            {
                'title': 'Discussion on neural networks',
                'link': 'https://reddit.com/r/MachineLearning/test',
                'score': 200,
                'comments': 50,
                'subreddit': 'MachineLearning'
            }
        ],
        'GitHub Trending': [
            {
                'full_name': 'openai/gpt-code',
                'link': 'https://github.com/openai/gpt-code',
                'description': 'GPT code generation tool',
                'language': 'Python',
                'stars': 5000,
                'stars_today': 200
            }
        ]
    }

    config = {
        'output_dir': 'reports',
        'date_format': '%Y-%m-%d',
        'include_summary': True
    }

    generator = MarkdownGenerator(config)
    filepath = generator.generate(test_data)

    print(f"\nReport generated: {filepath}\n")

    # Display content
    with open(filepath, 'r') as f:
        print(f.read())